describe('Tic Tac Toe Tests', () => {
  it('Size 3 Game Happy Path Vertical Victory', () => {
    cy.visit('https://roomy-fire-houseboat.glitch.me/')
    cy.get('[id="number"]').type('3')
    cy.get('[id="start"]').click()
    cy.get('[id="table"]')
    .children('tr')
    .children('td')
    .should('have.length', 9)
    cy.get('td').eq(0).click().should('contain', 'X')
    cy.get('td').eq(1).click().should('contain', 'O')
    cy.get('td').eq(3).click().should('contain', 'X')
    cy.get('td').eq(2).click().should('contain', 'O')
    cy.get('td').eq(6).click().should('contain', 'X')
    cy.get('[id="endgame"]').should('contain', "Congratulations player X! You've won. Refresh to play again!") //This step will fail because message says O won incorrectly
  })

  it('Input and Size Test', () => {
    cy.visit('https://roomy-fire-houseboat.glitch.me/')
    cy.get('[id="number"]').type('test')
    cy.get('[id="start"]').click()
    cy.get('[id="table"]')
    .children('tr').should('not.exist')
    cy.visit('https://roomy-fire-houseboat.glitch.me/')
    cy.get('[id="number"]').type('2')
    cy.get('[id="start"]').click()
    cy.get('[id="table"]')
    .children('tr')
    .children('td')
    .should('have.length', 4)
    cy.reload()
    cy.get('[id="number"]').type('4')
    cy.get('[id="start"]').click()
    cy.get('[id="table"]')
    .children('tr')
    .children('td')
    .should('have.length', 16)
    cy.reload()
    cy.get('[id="number"]').type('1')
    cy.get('[id="start"]').click()
    cy.get('[id="table"]')
    .children('tr')
    .children('td')
    .should('have.length', 1)
    cy.reload()
    cy.get('[id="number"]').type('10')
    cy.get('[id="start"]').click()
    cy.get('[id="table"]')
    .children('tr')
    .children('td')
    .should('have.length', 100)
    cy.reload()
    cy.get('[id="number"]').type('50')
    cy.get('[id="start"]').click()
    cy.get('[id="table"]')
    .children('tr')
    .children('td')
    .should('have.length', 2500)
  })

  it('Horizontal Size 2, Results Clear on Refresh, Diagonal Size 4 Test', () =>{
    cy.visit('https://roomy-fire-houseboat.glitch.me/')
    cy.get('[id="number"]').type('3')
    cy.get('[id="start"]').click()
    cy.get('td').eq(2).click().should('contain', 'X')
    cy.get('td').eq(1).click().should('contain', 'O')
    cy.get('td').eq(3).click().should('contain', 'X')
  //Disabling step so test continues  cy.get('[id="endgame"]').should('contain', "Congratulations player X! You've won. Refresh to play again!")
    cy.reload()
    cy.get('[id="table"]')
    .children('tr').should('not.exist')
    cy.get('[id="number"]').type('4')
    cy.get('[id="start"]').click()
    cy.get('[id="table"]')
    .children('tr')
    .children('td')
    .should('have.length', 16)
    cy.get('td').eq(2).click().should('contain', 'X')
    cy.get('td').eq(0).click().should('contain', 'O')
    cy.get('td').eq(9).click().should('contain', 'X')
    cy.get('td').eq(5).click().should('contain', 'O')
    cy.get('td').eq(1).click().should('contain', 'X')
    cy.get('td').eq(10).click().should('contain', 'O')
    cy.get('td').eq(13).click().should('contain', 'X')
    cy.get('td').eq(15).click().should('contain', 'O')
    cy.get('[id="endgame"]').should('contain', "Congratulations player O! You've won. Refresh to play again!") //This step will fail because message says X won incorrectly
  })
})